packages:
  '@twin-digital/eslint-config':
    rules:
      eslint: false
      eslint-config-bootstrap: false
  '@twin-digital/opus-scripts':
    rules:
      clean: false
      eslint: false
      eslint-config-bootstrap: false
      typescript: false
      typescript-dependencies: false
      typescript-scripts-and-dependencies: false
      typescript-with-options: false
  '@twin-digital/tsconfig':
    rules:
      eslint: false
      eslint-config-bootstrap: false
      typescript: false
      typescript-dependencies: false
      typescript-scripts-and-dependencies: false
      typescript-with-options: false

hooks:
  - description: Install dependencies
    path: package.json
    run: pnpm install
  - description: Reformat package.json
    path: package.json
    run: pnpm exec prettier-package-json --write ./package.json

features:
  - name: .nvmrc
    actions:
      - name: Create .nvmrc file
        action: write-file
        options:
          file: .nvmrc
          content: |
            lts/krypton
  - name: bundle
    actions:
      - name: Create tsdown config file
        action: write-file
        conditions:
          - dependency: tsdown
        options:
          file: tsdown.config.ts
          content: |
            import { defineConfig } from 'tsdown'

            export default defineConfig({
              dts: true,
              entry: 'src/**/*.ts',
              fixedExtension: false,
              hash: false,
              // noExternal: [/^@twin-digital\//],
              shims: true,
              unbundle: true,
            })
  - name: clean
    actions:
      - name: Add script
        action: json-merge-patch
        options:
          file: package.json
          patch: |
            scripts:
              clean: clean
            devDependencies:
              '@twin-digital/opus-scripts': workspace:*
  - name: docker
    actions:
      - name: Build container image
        action: json-merge-patch
        conditions:
          - exists: Dockerfile
        options:
          file: package.json
          patch: |
            scripts:
              artifact: artifact
            devDependencies:
              '@twin-digital/opus-scripts': workspace:*
  - name: engines
    actions:
      - name: Add engines specification to package.json
        action: json-merge-patch
        options:
          file: package.json
          patch: |
            engines:
              node: 24.x
              pnpm: 10.x
  - name: eslint
    actions:
      - action: write-file
        options:
          file: eslint.config.js
          content: |
            import base from '@twin-digital/eslint-config'

            export default base

      - action: json-merge-patch
        options:
          file: package.json
          patch: |
            scripts:
              lint: lint
              'lint:fix': lint_fix
            devDependencies:
              '@eslint/js': 'catalog:'
              '@twin-digital/eslint-config': workspace:*
              '@twin-digital/opus-scripts': workspace:*
              eslint: 'catalog:'
              eslint-config-prettier: 'catalog:'
              globals: 'catalog:'
              prettier: 'catalog:'
              prettier-package-json: 'catalog:'
              typescript-eslint: 'catalog:'
  - name: package-manifest
    actions:
      # if project has source files...
      - name: Add files entries
        action: json-patch
        conditions:
          - exists: src/*.ts
        options:
          file: package.json
          patch: |
            - opx: appendIfMissing
              path: /files
              value: dist
            - opx: appendIfMissing
              path: /files
              value: "!dist/**/*.d.ts.map"
      - name: Add default esm export
        action: json-merge-patch
        conditions:
          - exists: src/index.ts
        options:
          file: package.json
          patch: |
            exports:
              .:
                import:
                  types: ./dist/index.d.ts
                  import: ./dist/index.js
      - name: Forbid direct import of '/index'
        action: json-patch
        conditions:
          - exists: src/index.ts
        options:
          file: package.json
          patch: |
            - op: add
              path: /exports/.~1index
              value: null
            - op: add
              path: /exports/.~1index.js
              value: null
      - name: Add additional esm exports
        action: json-merge-patch
        conditions:
          - exists: src/*.ts
        options:
          file: package.json
          patch: |
            exports:
              ./*:
                import:
                  types: ./dist/*.d.ts
                  import: ./dist/*.js
      - name: Add default cjs export
        action: json-merge-patch
        conditions:
          - exists: tsconfig.cjs.json
          - exists: src/index.ts
        options:
          file: package.json
          patch: |
            exports:
              .:
                require:
                  types: ./dist/cjs/index.d.ts
                  require: ./dist/cjs/index.js
      - name: Add additional cjs exports
        action: json-merge-patch
        conditions:
          - exists: tsconfig.cjs.json
          - exists: src/*.ts
        options:
          file: package.json
          patch: |
            exports:
              ./*:
                require:
                  types: ./dist/cjs/*.d.ts
                  require: ./dist/cjs/*.js
      - name: Remove unnecessary cjs exports
        action: json-merge-patch
        conditions:
          - notExists: tsconfig.cjs.json
        options:
          file: package.json
          patch: |
            exports:
              .:
                require: null
              ./*:
                require: null
      # if project does not have source files...
      - name: Remove files entries
        action: json-patch
        conditions:
          - notExists: src/*
        options:
          file: package.json
          patch: |
            - opx: removeValue
              path: /files
              value: dist
            - opx: removeValue
              path: /files
              value: '!dist/**/*.d.ts.map'
      - name: Remove exports
        action: json-merge-patch
        conditions:
          - notExists: src/*.ts
        options:
          file: package.json
          patch: |
            exports:
              .: null
              ./*: null
  - name: test
    actions:
      - name: Add dependencies
        action: json-merge-patch
        conditions:
          - exists: src/**/*.test.ts
        options:
          file: package.json
          patch: |
            devDependencies:
              "@twin-digital/vitest-config": "workspace:*"
              "@vitest/coverage-istanbul": "catalog:"
              vitest: "catalog:"
            scripts:
                test: vitest run
                "test:watch": vitest
      - name: Create vitest config
        action: write-file
        conditions:
          - exists: src/**/*.test.ts
          - notExists: src/**/*.tsx
        options:
          file: vitest.config.ts
          content: |
            import { sharedConfig } from '@twin-digital/vitest-config'

            export default sharedConfig
      - name: Create vitest config (React support)
        action: write-file
        conditions:
          - exists: src/**/*.test.ts
          - exists: src/**/*.tsx
        options:
          file: vitest.config.ts
          content: |
            import { defineConfig, mergeConfig } from 'vitest/config'
            import { sharedConfig } from '@twin-digital/vitest-config'

            export default mergeConfig(
              sharedConfig,
              defineConfig({
                test: {
                  environment: 'jsdom',
                },
              }),
            )

  - name: typescript
    actions:
      - name: Create tsconfig.json file
        action: write-file
        conditions:
          - notExists: tsconfig.options.json
        options:
          file: tsconfig.json
          content: |
            {
              "extends": ["@twin-digital/tsconfig/tsconfig.json"]
            }
      - name: Create tsconfig.build.json file
        action: write-file
        conditions:
          - notExists: tsconfig.options.json
        options:
          file: tsconfig.build.json
          content: |
            {
              "extends": ["@twin-digital/tsconfig/tsconfig.build.json"]
            }
      - name: Create tsconfig.json file with custom options
        action: write-file
        conditions:
          - exists: tsconfig.options.json
        options:
          file: tsconfig.json
          content: |
            {
              "extends": ["@twin-digital/tsconfig/tsconfig.json", "./tsconfig.options.json"]
            }
      - name: Create tsconfig.build.json file with custom options
        action: write-file
        conditions:
          - exists: tsconfig.options.json
        options:
          file: tsconfig.build.json
          content: |
            {
              "extends": ["@twin-digital/tsconfig/tsconfig.build.json", "./tsconfig.options.json"]
            }
      - name: Add scripts and dependencies
        action: json-merge-patch
        options:
          file: package.json
          patch: |
            scripts:
              build: build
              typecheck: tsc --noEmit
            devDependencies:
              '@twin-digital/opus-scripts': workspace:*
              '@twin-digital/tsconfig': workspace:*
              '@types/node': 'catalog:'
              typescript: 'catalog:'
