packages:
  - nodejs/**

onlyBuiltDependencies:
  - esbuild

catalog:
  '@eslint/js': ^9.29.0
  eslint: ^9.29.0
  eslint-config-prettier: ^10.1.5
  globals: ^16.0.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  typescript-eslint: ^8.34.1
