packages:
  - nodejs/*
  - nodejs/*/*
  - tooling/scripts

catalog:
  '@eslint/js': ^9.29.0
  '@types/node': 24.10.1
  eslint: ^9.29.0
  eslint-config-prettier: ^10.1.5
  globals: ^16.0.0
  prettier: ^3.5.3
  prettier-package-json: ^2.8.0
  typescript: ^5.9.3
  typescript-eslint: ^8.47.0
  vitest: ^4.0.12
  '@vitest/coverage-istanbul': ^4.0.12

onlyBuiltDependencies:
  - esbuild
  - hnswlib-node
  - serverless

patchedDependencies:
  ink: patches/ink.patch
  '@mishieck/ink-titled-box@0.3.0': patches/@mishieck__ink-titled-box@0.3.0.patch
