import { randomInt } from 'node:crypto'

import type { FileTree } from './tree.js'

const ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyz'

/**
 * The ratified prefixes: `r- d- q- b- f-` at one letter, `run-` at three (d-kqofgshc). `b` ids
 * name backlog items and are generated by the backlog commands, not by `design-process id`.
 */
export type IdKind = 'r' | 'd' | 'q' | 'b' | 'f' | 'run'

/** An opaque fact id. Facts with such an id are cited bare; a slug id needs the `f:` prefix. */
export const FACT_ID = /^f-[0-9a-z]{8}$/

/**
 * Every id-shaped token mentioned anywhere under products/, facts/, and evidence/ — declarations
 * and citations alike. Facts and runs share one pool namespace with the claim ids (d-kqofgshc).
 */
export const collectIds = (tree: FileTree): Set<string> => {
  const ids = new Set<string>()
  const scanned = (path: string) =>
    (path.startsWith('products/') || path.startsWith('facts/') || path.startsWith('evidence/')) &&
    (path.endsWith('.yaml') || path.endsWith('.yml'))
  for (const path of tree.paths().filter(scanned)) {
    for (const match of tree.read(path).matchAll(/\b(?:[rdqf]|run)-[0-9a-z]{8}\b/g)) {
      ids.add(match[0])
    }
  }
  return ids
}

/** Generate opaque ids — {prefix}-{8 random lowercase base36 characters} — avoiding the taken set. */
export const generateIds = (kind: IdKind, count: number, taken: ReadonlySet<string>): string[] => {
  const generated: string[] = []
  const seen = new Set(taken)
  while (generated.length < count) {
    const id = `${kind}-${Array.from({ length: 8 }, () => ALPHABET[randomInt(ALPHABET.length)]).join('')}`
    if (!seen.has(id)) {
      seen.add(id)
      generated.push(id)
    }
  }
  return generated
}
