name: Deploy via Serverless
description: Configure AWS credentials via OIDC and then run Serverless Framework

inputs:
  aws-region:
    description: AWS region (e.g. us-east-2)
    required: true
  operation:
    description: Which Turbo task to run - `"deploy"` or `"destroy"`
    required: false
    default: deploy
  role-arn:
    description: The AWS OIDC Role ARN to assume
    required: true
  serverless-access-key:
    description: Serverless Framework Dashboard access key
    required: true
  stage:
    description: Which Serverless stage to deploy (e.g. "preview", "prod")
    required: true

runs:
  using: composite
  steps:
    - name: Validate `operation` input
      shell: bash
      run: |
        case "${{ inputs.operation }}" in
          deploy|destroy) 
            ;; 
          *) 
            echo "::error ::Invalid operation: '${{ inputs.operation }}'. Must be 'deploy' or 'destroy'."
            exit 1
            ;;
        esac
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.aws-region }}
    - name: Run `serverless ${{ inputs.operation }}`
      env:
        SERVERLESS_ACCESS_KEY: ${{ inputs.serverless-access-key }}
      run: |
        pnpm exec turbo run "${{ inputs.operation }}" -- \
          --stage "${{ inputs.stage }}" \
          --region "${{ inputs.aws-region }}"
      shell: bash
