export interface InstrumentFamily {
  /**
   * 0-based number of the first patch in this family.
   */
  firstPatch: number

  /**
   * Ordinal used to define the order in which this family is presented. For GM1/GM2 families, these should be in the
   * standard order of the patches the families contain (0-15). For non-standard families, the index will be >15.
   */
  index: number

  /**
   * 0-based number of the last patch in this family.
   */
  lastPatch: number

  /**
   * Human readable name of this instrument family.
   */
  name: string
}

export interface Instrument {
  /**
   * Bank used to select this instrument.
   */
  bank: {
    lsb: number
    msb: number
  }

  /**
   * Name of the `family`, or category, this instrument belongs to. If `standard` is "gm1" or "gm2" this will be the
   * family name specified by that standard, otherwise the value depends on the instrument's source.
   */
  family: string

  /**
   * Unique identifier for this instrument in the instrument set. Format: `${patch}#${bank.msb}#${bank.lsb}`
   */
  id: string

  /**
   * Human-readable name of this instrument.
   */
  name: string

  /**
   * MIDI patch number (0–127) used to select this instrument.
   */
  patch: number

  /**
   * What MIDI standard introduced this instrument, or `none` for non-standard instruments.
   */
  standard: 'gm1' | 'gm2' | 'none'
}

export const InstrumentFamilies = [
  { firstPatch: 0, lastPatch: 7, index: 0, name: 'Piano' },
  { firstPatch: 8, lastPatch: 15, index: 1, name: 'Chromatic Percussion' },
  { firstPatch: 16, lastPatch: 23, index: 2, name: 'Organ' },
  { firstPatch: 24, lastPatch: 31, index: 3, name: 'Guitar' },
  { firstPatch: 32, lastPatch: 39, index: 4, name: 'Bass' },
  { firstPatch: 40, lastPatch: 47, index: 5, name: 'Orchestra Solo' },
  { firstPatch: 48, lastPatch: 55, index: 6, name: 'Orchestra Ensemble' },
  { firstPatch: 56, lastPatch: 63, index: 7, name: 'Brass' },
  { firstPatch: 64, lastPatch: 71, index: 8, name: 'Reed' },
  { firstPatch: 72, lastPatch: 79, index: 9, name: 'Wind' },
  { firstPatch: 80, lastPatch: 87, index: 10, name: 'Synth Lead' },
  { firstPatch: 88, lastPatch: 95, index: 11, name: 'Synth Pad' },
  { firstPatch: 96, lastPatch: 103, index: 12, name: 'Synth Sound FX' },
  { firstPatch: 104, lastPatch: 111, index: 13, name: 'Ethnic' },
  { firstPatch: 112, lastPatch: 119, index: 14, name: 'Percussive' },
  { firstPatch: 120, lastPatch: 127, index: 15, name: 'Sound Effect' },
  { firstPatch: 0, lastPatch: 56, index: 16, name: 'Drum Kit' },
] as const satisfies InstrumentFamily[]

export type InstrumentFamilyName = (typeof InstrumentFamilies)[number]['name']

// ─── Piano (MSB=121) ─────────────────────────────────────────────────────────────
export const pianoInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 0,
    name: 'Acoustic Grand Piano',
    id: `0#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 0,
    name: 'Wide Acoustic Grand Piano',
    id: `0#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 1,
    name: 'Bright Acoustic Piano',
    id: `1#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 1,
    name: 'Wide Bright Acoustic Piano',
    id: `1#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 2,
    name: 'Electric Grand Piano',
    id: `2#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 2,
    name: 'Wide Electric Grand Piano',
    id: `2#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 3,
    name: 'Honky-tonk Piano',
    id: `3#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 3,
    name: 'Wide Honky-tonk Piano',
    id: `3#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 4,
    name: 'Rhodes Electric Piano',
    id: `4#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 4,
    name: 'Detuned Electric Piano 1',
    id: `4#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Piano',
    patch: 4,
    name: 'Variation Electric Piano 1',
    id: `4#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Piano',
    patch: 4,
    name: '60s Electric Piano',
    id: `4#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 5,
    name: 'Chorused Electric Piano',
    id: `5#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 5,
    name: 'Detuned Electric Piano 2',
    id: `5#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Piano',
    patch: 5,
    name: 'Variation Electric Piano 2',
    id: `5#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Piano',
    patch: 5,
    name: 'Electric Piano Legend',
    id: `5#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Piano',
    patch: 5,
    name: 'Phaser Electric Piano',
    id: `5#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 6,
    name: 'Harpsichord',
    id: `6#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 6,
    name: 'Coupled Harpsichord',
    id: `6#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Piano',
    patch: 6,
    name: 'Wide Harpsichord',
    id: `6#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Piano',
    patch: 6,
    name: 'Open Harpsichord',
    id: `6#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Piano',
    patch: 7,
    name: 'Clavinet',
    id: `7#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Piano',
    patch: 7,
    name: 'Pulsed Clavinet',
    id: `7#121#1`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Chromatic Percussion (MSB=121) ─────────────────────────────────────────────
export const chromaticPercussionInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 8,
    name: 'Celesta',
    id: `8#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 9,
    name: 'Glockenspiel',
    id: `9#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 10,
    name: 'Music Box',
    id: `10#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 11,
    name: 'Vibraphone',
    id: `11#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Chromatic Percussion',
    patch: 11,
    name: 'Wet Vibraphone',
    id: `11#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 12,
    name: 'Marimba',
    id: `12#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Chromatic Percussion',
    patch: 12,
    name: 'Wide Marimba',
    id: `12#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 13,
    name: 'Xylophone',
    id: `13#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 14,
    name: 'Tubular Bells',
    id: `14#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Chromatic Percussion',
    patch: 14,
    name: 'Church Bells',
    id: `14#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Chromatic Percussion',
    patch: 14,
    name: 'Carillon Bells',
    id: `14#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Chromatic Percussion',
    patch: 15,
    name: 'Dulcimer/Santur',
    id: `15#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Organ (MSB=121) ───────────────────────────────────────────────────────────────
export const organInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 16,
    name: 'Drawbar Organ 1',
    id: `16#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Organ',
    patch: 16,
    name: 'Detuned Drawbar Organ',
    id: `16#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Organ',
    patch: 16,
    name: '60s Drawbar Organ',
    id: `16#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Organ',
    patch: 16,
    name: 'Drawbar Organ 2',
    id: `16#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 17,
    name: 'Percussive B3 Organ 1',
    id: `17#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Organ',
    patch: 17,
    name: 'Detuned Percussive B3 Organ',
    id: `17#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Organ',
    patch: 17,
    name: 'Percussive B3 Organ 2',
    id: `17#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 18,
    name: 'Rock Organ',
    id: `18#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 19,
    name: 'Church Organ 1',
    id: `19#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Organ',
    patch: 19,
    name: 'Church Organ 2',
    id: `19#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Organ',
    patch: 19,
    name: 'Church Organ 3',
    id: `19#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 20,
    name: 'Reeds Organ',
    id: `20#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Organ',
    patch: 20,
    name: 'Puffs Organ',
    id: `20#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 21,
    name: 'French Accordion',
    id: `21#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Organ',
    patch: 21,
    name: 'Italian Accordion',
    id: `21#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 22,
    name: 'Harmonica',
    id: `22#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Organ',
    patch: 23,
    name: 'Tango Accordion',
    id: `23#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Guitar (MSB=121) ─────────────────────────────────────────────────────────────
export const guitarInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 24,
    name: 'Nylon-Strings Guitar 1',
    id: `24#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 24,
    name: 'Ukulele',
    id: `24#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Guitar',
    patch: 24,
    name: 'Opened Nylon-Strings Guitar',
    id: `24#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Guitar',
    patch: 24,
    name: 'Nylon-Strings Guitar 2',
    id: `24#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 25,
    name: 'Steel-Strings Guitar',
    id: `25#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 25,
    name: '12-Strings Steel Guitar',
    id: `25#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Guitar',
    patch: 25,
    name: 'Mandolin',
    id: `25#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Guitar',
    patch: 25,
    name: 'Steel-Strings Guitar + Body Tapped Sounds',
    id: `25#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 26,
    name: 'Jazz Guitar',
    id: `26#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 26,
    name: 'Hawaiian Guitar',
    id: `26#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 27,
    name: 'Clean Electric Guitar',
    id: `27#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 27,
    name: 'Chorus Guitar',
    id: `27#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Guitar',
    patch: 27,
    name: 'Mid Tone Guitar',
    id: `27#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 28,
    name: 'Muted Electric Guitar',
    id: `28#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 28,
    name: 'Funky Guitar 1',
    id: `28#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Guitar',
    patch: 28,
    name: 'Funky Guitar 2',
    id: `28#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Guitar',
    patch: 28,
    name: 'Jazz Man',
    id: `28#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 29,
    name: 'Overdriven Guitar',
    id: `29#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 29,
    name: 'Guitar Pinch',
    id: `29#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 30,
    name: 'Distortion Guitar',
    id: `30#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 30,
    name: 'Feedback Guitar',
    id: `30#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Guitar',
    patch: 30,
    name: 'Distortion Rhythm Guitar',
    id: `30#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Guitar',
    patch: 31,
    name: 'Guitar Harmonics',
    id: `31#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Guitar',
    patch: 31,
    name: 'Guitar Feedback',
    id: `31#121#1`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Bass (MSB=121) ───────────────────────────────────────────────────────────────
export const bassInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 32,
    name: 'Acoustic Bass',
    id: `32#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 33,
    name: 'Fingered Bass',
    id: `33#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Bass',
    patch: 33,
    name: 'Fingered Slap Bass',
    id: `33#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 34,
    name: 'Picked Bass',
    id: `34#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 35,
    name: 'Fretless Bass',
    id: `35#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 36,
    name: 'Slap Bass 1',
    id: `36#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 37,
    name: 'Slap Bass 2',
    id: `37#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 38,
    name: 'Synth Bass 1',
    id: `38#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Bass',
    patch: 38,
    name: 'Synth Bass 101',
    id: `38#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Bass',
    patch: 38,
    name: 'Synth Bass 3',
    id: `38#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Bass',
    patch: 38,
    name: 'Clavi Bass',
    id: `38#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Bass',
    patch: 38,
    name: 'Hammered Bass',
    id: `38#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Bass',
    patch: 39,
    name: 'Synth Bass 2',
    id: `39#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Bass',
    patch: 39,
    name: 'Synth Bass 4',
    id: `39#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Bass',
    patch: 39,
    name: 'Rubber Bass',
    id: `39#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Bass',
    patch: 39,
    name: 'Attack Pulsed',
    id: `39#121#3`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Orchestra Solo (MSB=121) ───────────────────────────────────────────────────
export const orchestraSoloInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 40,
    name: 'Violin',
    id: `40#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Solo',
    patch: 40,
    name: 'Slow Violin',
    id: `40#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 41,
    name: 'Viola',
    id: `41#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 42,
    name: 'Cello',
    id: `42#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 43,
    name: 'Contrabass',
    id: `43#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 44,
    name: 'Tremolo Strings',
    id: `44#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 45,
    name: 'Pizzicato Strings',
    id: `45#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 46,
    name: 'Harp',
    id: `46#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Solo',
    patch: 46,
    name: 'Yang Qin',
    id: `46#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Solo',
    patch: 47,
    name: 'Timpani',
    id: `47#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Orchestra Ensemble (MSB=121) ───────────────────────────────────────────────
export const orchestraEnsembleInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 48,
    name: 'Strings Ensemble',
    id: `48#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Ensemble',
    patch: 48,
    name: 'Orchestral Strings',
    id: `48#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Orchestra Ensemble',
    patch: 48,
    name: '60s Strings',
    id: `48#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 49,
    name: 'Slow Strings Ensemble',
    id: `49#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 50,
    name: 'Synth Strings 1',
    id: `50#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Ensemble',
    patch: 50,
    name: 'Synth Strings 3',
    id: `50#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 51,
    name: 'Synth Strings 2',
    id: `51#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 52,
    name: 'Choir Aahs 1',
    id: `52#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Ensemble',
    patch: 52,
    name: 'Choir Aahs 2',
    id: `52#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 53,
    name: 'Voice Oohs',
    id: `53#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Ensemble',
    patch: 53,
    name: 'Humming',
    id: `53#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 54,
    name: 'Synth Voice',
    id: `54#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Ensemble',
    patch: 54,
    name: 'Analog Voice',
    id: `54#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Orchestra Ensemble',
    patch: 55,
    name: 'Orchestral Hit',
    id: `55#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Orchestra Ensemble',
    patch: 55,
    name: 'Bass Hit',
    id: `55#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Orchestra Ensemble',
    patch: 55,
    name: '6th Hit',
    id: `55#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Orchestra Ensemble',
    patch: 55,
    name: 'Euro Hit',
    id: `55#121#3`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Brass (MSB=121) ──────────────────────────────────────────────────────────────
export const brassInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 56,
    name: 'Trumpet',
    id: `56#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 56,
    name: 'Dark Trumpet Soft',
    id: `56#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 57,
    name: 'Trombone 1',
    id: `57#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 57,
    name: 'Trombone 2',
    id: `57#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Brass',
    patch: 57,
    name: 'Bright Trombone',
    id: `57#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 58,
    name: 'Tuba',
    id: `58#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 59,
    name: 'Muted Trumpet 1',
    id: `59#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 59,
    name: 'Muted Trumpet 2',
    id: `59#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 60,
    name: 'French Horns 1',
    id: `60#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 60,
    name: 'French Horns 2',
    id: `60#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 61,
    name: 'Brass Section 1',
    id: `61#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 61,
    name: 'Brass Section 2',
    id: `61#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 62,
    name: 'Synth Brass 1',
    id: `62#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 62,
    name: 'Synth Brass 3',
    id: `62#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Brass',
    patch: 62,
    name: 'Analog Brass 1',
    id: `62#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Brass',
    patch: 62,
    name: 'Jump Brass',
    id: `62#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Brass',
    patch: 63,
    name: 'Synth Brass 2',
    id: `63#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Brass',
    patch: 63,
    name: 'Synth Brass 4',
    id: `63#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Brass',
    patch: 63,
    name: 'Analog Brass 2',
    id: `63#121#2`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Reed (MSB=121) ───────────────────────────────────────────────────────────────
export const reedInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 64,
    name: 'Soprano Sax',
    id: `64#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 65,
    name: 'Alto Sax',
    id: `65#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 66,
    name: 'Tenor Sax',
    id: `66#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 67,
    name: 'Baritone Sax',
    id: `67#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 68,
    name: 'Oboe',
    id: `68#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 69,
    name: 'English Horn',
    id: `69#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 70,
    name: 'Bassoon',
    id: `70#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Reed',
    patch: 71,
    name: 'Clarinet',
    id: `71#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Wind (MSB=121) ───────────────────────────────────────────────────────────────
export const windInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 72,
    name: 'Piccolo',
    id: `72#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 73,
    name: 'Flute',
    id: `73#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 74,
    name: 'Recorder',
    id: `74#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 75,
    name: 'Pan Flute',
    id: `75#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 76,
    name: 'Bottle Blow',
    id: `76#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 77,
    name: 'Shakuhachi',
    id: `77#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 78,
    name: 'Whistle',
    id: `78#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Wind',
    patch: 79,
    name: 'Ocarina',
    id: `79#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Synth Lead (MSB=121) ─────────────────────────────────────────────────────────
export const synthLeadInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 80,
    name: 'Square Lead',
    id: `80#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Lead',
    patch: 80,
    name: 'Square Wave',
    id: `80#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Synth Lead',
    patch: 80,
    name: 'Sine Wave',
    id: `80#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 81,
    name: 'Saw Lead',
    id: `81#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Lead',
    patch: 81,
    name: 'Saw Wave',
    id: `81#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Synth Lead',
    patch: 81,
    name: 'Doctor Solo',
    id: `81#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Synth Lead',
    patch: 81,
    name: 'Natural Lead',
    id: `81#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Synth Lead',
    patch: 81,
    name: 'Sequenced Saw',
    id: `81#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 82,
    name: 'Synth Calliope',
    id: `82#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 83,
    name: 'Chiffer Lead',
    id: `83#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 84,
    name: 'Charang',
    id: `84#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Lead',
    patch: 84,
    name: 'Wire Lead',
    id: `84#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 85,
    name: 'Solo Synth Vox',
    id: `85#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 86,
    name: '5th Saw Wave',
    id: `86#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Lead',
    patch: 87,
    name: 'Bass & Lead',
    id: `87#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Lead',
    patch: 87,
    name: 'Delayed Lead',
    id: `87#121#1`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Synth Pad (MSB=121) ──────────────────────────────────────────────────────────
export const synthPadInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 88,
    name: 'Fantasia Pad',
    id: `88#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 89,
    name: 'Warm Pad',
    id: `89#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Pad',
    patch: 89,
    name: 'Sine Pad',
    id: `89#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 90,
    name: 'Polysynth Pad',
    id: `90#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 91,
    name: 'Space Voice Pad',
    id: `91#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Pad',
    patch: 91,
    name: 'Itopia',
    id: `91#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 92,
    name: 'Bowed Glass Pad',
    id: `92#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 93,
    name: 'Metal Pad',
    id: `93#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 94,
    name: 'Halo Pad',
    id: `94#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Pad',
    patch: 95,
    name: 'Sweep Pad',
    id: `95#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Synth Sound FX (MSB=121) ────────────────────────────────────────────────────
export const synthSoundFxInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 96,
    name: 'Ice Rain',
    id: `96#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 97,
    name: 'Soundtrack',
    id: `97#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 98,
    name: 'Crystal',
    id: `98#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Sound FX',
    patch: 98,
    name: 'Synth Mallet',
    id: `98#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 99,
    name: 'Atmosphere',
    id: `99#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 100,
    name: 'Brightness',
    id: `100#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 101,
    name: 'Goblin',
    id: `101#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 102,
    name: 'Echo Drops',
    id: `102#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Synth Sound FX',
    patch: 102,
    name: 'Echo Bell',
    id: `102#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Synth Sound FX',
    patch: 102,
    name: 'Echo Pan',
    id: `102#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Synth Sound FX',
    patch: 103,
    name: 'Star Theme',
    id: `103#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Ethnic (MSB=121) ─────────────────────────────────────────────────────────────
export const ethnicInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 104,
    name: 'Sitar 1',
    id: `104#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Ethnic',
    patch: 104,
    name: 'Sitar 2',
    id: `104#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 105,
    name: 'Banjo',
    id: `105#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 106,
    name: 'Shamisen',
    id: `106#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 107,
    name: 'Koto',
    id: `107#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Ethnic',
    patch: 107,
    name: 'Taisho Koto',
    id: `107#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 108,
    name: 'Kalimba',
    id: `108#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 109,
    name: 'Bagpipe',
    id: `109#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 110,
    name: 'Fiddle',
    id: `110#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Ethnic',
    patch: 111,
    name: 'Shanai',
    id: `111#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Percussive (MSB=121) ─────────────────────────────────────────────────────────
export const percussiveInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 112,
    name: 'Tinkle Bells',
    id: `112#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 113,
    name: 'Agogô',
    id: `113#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 114,
    name: 'Steel Drums',
    id: `114#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 115,
    name: 'Woodblock',
    id: `115#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Percussive',
    patch: 115,
    name: 'Castanets',
    id: `115#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 116,
    name: 'Taiko Drums',
    id: `116#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Percussive',
    patch: 116,
    name: 'Concert Bass Drums',
    id: `116#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 117,
    name: 'Melodic Tom 1',
    id: `117#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Percussive',
    patch: 117,
    name: 'Melodic Tom 2',
    id: `117#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 118,
    name: 'Synth Drums',
    id: `118#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Percussive',
    patch: 118,
    name: '808 Toms',
    id: `118#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Percussive',
    patch: 118,
    name: 'Electric Percussion',
    id: `118#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Percussive',
    patch: 119,
    name: 'Reversed Cymbals',
    id: `119#121#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Sound Effect (MSB=121) ──────────────────────────────────────────────────────
export const soundEffectInstruments = [
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 120,
    name: 'Guitar Fret Noise',
    id: `120#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 120,
    name: 'Guitar Cut Noise',
    id: `120#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 120,
    name: 'String Slap',
    id: `120#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 121,
    name: 'Breath Noise',
    id: `121#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 121,
    name: 'Flute Key Click',
    id: `121#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 122,
    name: 'Seashore',
    id: `122#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 122,
    name: 'Rain',
    id: `122#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 122,
    name: 'Thunder',
    id: `122#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Sound Effect',
    patch: 122,
    name: 'Wind',
    id: `122#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Sound Effect',
    patch: 122,
    name: 'Stream',
    id: `122#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 5 },
    family: 'Sound Effect',
    patch: 122,
    name: 'Bubble',
    id: `122#121#5`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 123,
    name: 'Bird',
    id: `123#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 123,
    name: 'Dog',
    id: `123#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 123,
    name: 'Horse-Gallop',
    id: `123#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Sound Effect',
    patch: 123,
    name: 'Bird 2',
    id: `123#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 124,
    name: 'Telephone 1',
    id: `124#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 124,
    name: 'Telephone 2',
    id: `124#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 124,
    name: 'Door Creaking',
    id: `124#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Sound Effect',
    patch: 124,
    name: 'Door Closing',
    id: `124#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Sound Effect',
    patch: 124,
    name: 'Scratch',
    id: `124#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 5 },
    family: 'Sound Effect',
    patch: 124,
    name: 'Wind Chimes',
    id: `124#121#5`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Helicopter',
    id: `125#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Car-Engine',
    id: `125#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Car-Stop',
    id: `125#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Car-Pass',
    id: `125#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Car-Crash',
    id: `125#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 5 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Siren',
    id: `125#121#5`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 6 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Train',
    id: `125#121#6`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 7 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Jetplane',
    id: `125#121#7`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 8 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Starship',
    id: `125#121#8`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 9 },
    family: 'Sound Effect',
    patch: 125,
    name: 'Burst Noise',
    id: `125#121#9`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 126,
    name: 'Applause',
    id: `126#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 126,
    name: 'Laughing',
    id: `126#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 126,
    name: 'Screaming',
    id: `126#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Sound Effect',
    patch: 126,
    name: 'Punch',
    id: `126#121#3`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 4 },
    family: 'Sound Effect',
    patch: 126,
    name: 'Heart Beat',
    id: `126#121#4`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 5 },
    family: 'Sound Effect',
    patch: 126,
    name: 'Footsteps',
    id: `126#121#5`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 0 },
    family: 'Sound Effect',
    patch: 127,
    name: 'Gun Shot',
    id: `127#121#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 121, lsb: 1 },
    family: 'Sound Effect',
    patch: 127,
    name: 'Machine Gun',
    id: `127#121#1`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 2 },
    family: 'Sound Effect',
    patch: 127,
    name: 'Lasergun',
    id: `127#121#2`,
    standard: 'gm2',
  },
  {
    bank: { msb: 121, lsb: 3 },
    family: 'Sound Effect',
    patch: 127,
    name: 'Explosion',
    id: `127#121#3`,
    standard: 'gm2',
  },
] satisfies Instrument[]

// ─── Drum Kit (MSB=120) ───────────────────────────────────────────────────────────
export const drumKitInstruments = [
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 0,
    name: 'Standard Kit',
    id: `0#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 8,
    name: 'Room Kit',
    id: `8#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 16,
    name: 'Power Kit',
    id: `16#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 24,
    name: 'Electronic Kit',
    id: `24#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 25,
    name: 'TR-808 Kit',
    id: `25#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 32,
    name: 'Jazz Kit',
    id: `32#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 40,
    name: 'Brush Kit',
    id: `40#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 48,
    name: 'Orchestra Kit',
    id: `48#120#0`,
    standard: 'gm1',
  },
  {
    bank: { msb: 120, lsb: 0 },
    family: 'Drum Kit',
    patch: 56,
    name: 'Sound FX Kit',
    id: `56#120#0`,
    standard: 'gm1',
  },
] satisfies Instrument[]

// ─── Combined Array ──────────────────────────────────────────────────────────────
export const Gm2Instruments = [
  ...pianoInstruments,
  ...chromaticPercussionInstruments,
  ...organInstruments,
  ...guitarInstruments,
  ...bassInstruments,
  ...orchestraSoloInstruments,
  ...orchestraEnsembleInstruments,
  ...brassInstruments,
  ...reedInstruments,
  ...windInstruments,
  ...synthLeadInstruments,
  ...synthPadInstruments,
  ...synthSoundFxInstruments,
  ...ethnicInstruments,
  ...percussiveInstruments,
  ...soundEffectInstruments,
  ...drumKitInstruments,
] satisfies Instrument[]
