import { randomUUID } from 'node:crypto'
import { InputLayer, type InputLayerOptions } from './input-controller.js'
import { useEffect, type DependencyList } from 'react'
import { useUi } from '../store/hooks.js'

export type InputLayerConfigFn = (layer: InputLayer) => void

type LayerOptions = Pick<InputLayerOptions, 'global' | 'priority'>
interface HookOptions {
  /**
   * Whether this input layer is enabled or not. If the layer is disabled, nothing will be registered.
   * @defaultValue true
   */
  enabled?: boolean

  /**
   * Optional ID used to operate on this layer after it's registered. A UUID will be generated by default.
   */
  id?: string
}

/**
 * Register an `InputLayer` for the lifetime of a component.
 *
 * The hook will create a new `InputLayer`, call `configureLayer` so the caller
 * can add actions, then register the layer with the global input controller.
 * When the component unmounts (or `enabled` flips to `false`) the layer is
 * removed.
 *
 * @param configureLayer - Callback that receives the newly-created `InputLayer`.
 *   Use this to call `addAction` and configure the layer's behavior.
 * @param options - Hook options:
 *   - `enabled` (default: `true`) — when `false` the layer is not created or
 *     registered.
 *   - `id` — optional id to use for the layer; a UUID is generated by default.
 *   - `global` / `priority` — passed through to the `InputLayer` constructor.
 * @param dependencies - Optional dependency list that will be spread into the
 *   underlying `useEffect` dependency array. Include any values that your
 *   `configureLayer` callback closes over so the layer is recreated when they
 *   change.
 * @returns void
 *
 * @example
 * ```ts
 * useInputLayer((layer) => {
 *   layer.addAction('a', () => doSomething(), 'do something')
 * }, { enabled: focused, id: 'my-layer', priority: 20 }, [focused])
 * ```
 */
export const useInputLayer = (
  configureLayer: InputLayerConfigFn,
  { enabled = true, id, ...options }: HookOptions & LayerOptions = {},
  dependencies: DependencyList = [],
) => {
  const ui = useUi()
  const input = ui.input

  useEffect(() => {
    if (!enabled) {
      return
    }

    const layer = new InputLayer(id ?? randomUUID(), {
      global: options.global,
      priority: options.priority,
    })
    configureLayer(layer)

    input.register(layer)
    return () => {
      input.remove(layer.id)
    }
  }, [enabled, id, input, options.global, options.priority, ...dependencies])
}
